credentials:
  usernames:
    brunocatani:
      email: brunohcatani@gmail.com
      name: Bruno Catani
      password: $2b$12$JIaq4rnCRb0WMxK51BbwEuyAuivkRQx2cHkyY5AFhs3dyV7S.J6ju # To be replaced with hashed password
    mariaduda:
      email: 
      name: Maria Eduarda
      password: $2b$12$T09zNT05AM1WvJMK2ptVAeW.Gzf0XjDFrgCyo22kcKETmfKUhDgUy # To be replaced with hashed password
cookie:
  expiry_days: 0
  key: chocolate # Must be string
  name: cookie
preauthorized:
  emails:
  - brunohcatani@gmail.com
